services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6_result
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_DASHBOARDS_JSON_PATH: '/var/lib/grafana/dashboards'
      GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE: 'true'
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      INFLUXDB_DB: k6_result
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    depends_on:
      - influxdb
    volumes:
      - ./scripts:/scripts
    entrypoint: ["k6"]
    command: ["run", "/scripts/example.js", "--out", "influxdb=http://influxdb:8086/k6_result"]

